[tox]
envlist = py314, py313, py312, py311, py310
isolated_build = True

[gh-actions]
python:
  3.14: py314
  3.13: py313
  3.12: py312
  3.11: py311
  3.10: py310
  

[testenv]
deps =
     pytest
     pytest-cov
     numpy
     scipy
     tomlkit
commands =
    python -m pytest
